/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCascaderMenu: typeof import('element-plus/es')['ElCascaderMenu']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
  const ElDropdownCollectionItem: typeof import('element-plus/es')['ElDropdownCollectionItem']
  const ElFocusGroupCollection: typeof import('element-plus/es')['ElFocusGroupCollection']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOverlay: typeof import('element-plus/es')['ElOverlay']
  const ElRovingFocusCollectionItem: typeof import('element-plus/es')['ElRovingFocusCollectionItem']
  const ElSelectMenu: typeof import('element-plus/es')['ElSelectMenu']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElTreeNode: typeof import('element-plus/es')['ElTreeNode']
}
